// <auto-generated />
using System;
using GerenciamentoFinanceiro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoFinanceiro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciamentoFinanceiro.Models.Categoria", b =>
                {
                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = "educacao",
                            Nome = "Educação"
                        },
                        new
                        {
                            CategoriaId = "salario",
                            Nome = "Salário"
                        },
                        new
                        {
                            CategoriaId = "alimentacao",
                            Nome = "Alimentação"
                        },
                        new
                        {
                            CategoriaId = "comissao",
                            Nome = "Comissão"
                        });
                });

            modelBuilder.Entity("GerenciamentoFinanceiro.Models.Financeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransacaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TransacaoId");

                    b.ToTable("Financas");
                });

            modelBuilder.Entity("GerenciamentoFinanceiro.Models.Transacao", b =>
                {
                    b.Property<string>("TransacaoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransacaoId");

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            TransacaoId = "ganho",
                            Nome = "Ganho"
                        },
                        new
                        {
                            TransacaoId = "despesa",
                            Nome = "Despesa"
                        });
                });

            modelBuilder.Entity("GerenciamentoFinanceiro.Models.Financeiro", b =>
                {
                    b.HasOne("GerenciamentoFinanceiro.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciamentoFinanceiro.Models.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Transacao");
                });
#pragma warning restore 612, 618
        }
    }
}
